const translations = {
    en: {
      title: "Léandre Postal",
      aboutMeTitle: "About Me",
      aboutMeText1: "Hello, my name is Léandre, and I recently graduated with a bachelor's degree in computer science from the University of Sherbrooke (co-op program).",
      aboutMeText2: "I am motivated by technological challenges and the idea of providing innovative solutions through my technical skills and professional rigor.",
      interestsTitle: "My Interests",
      sports: "Sports",
      sportsDescription: "I enjoy sports like triathlon, ultimate frisbee, and volleyball. Outdoor sports also interest me!",
      innovations: "Innovations",
      innovationsDescription: "I like exploring new approaches, tools, and frameworks to deliver efficient and user-centered solutions.",
      graphics: "Graphics",
      graphicsDescription: "I enjoy designing, modeling, and drawing new ideas. From Krita to Blender, I love starting creative projects.",
      skillsTitle: "My Skills",
      teamwork: "Teamwork",
      curiosity: "Curiosity",
      leadership: "Leadership",
      workTitle: "Work Experience",
      educationTitle: "Education",
      projectsTitle: "Projects",
      downloadCV: "Download CV",
      footer: "© 2024 Léandre Postal. All Rights Reserved.",
      we1Title: "Analyst Programmer at the ",
      we1Place: "",
      we1Time: "Summer and fall 2024 sessions, T4 internship and part-time job",
      we1Description: "Development of a REST API in Java to create and modify student data at the university. Use of Java, Spring Boot, GitLab and Docker.",
      we2Title: "Full-stack developer at",
      we2Place: "",
      we2Time: "Winter 2024 session, part-time job",
      we2Description: "Implementation of a page for generating contracts and sending documents. Use of Blazor, C#, SQL server, Docusign API.",
      we3Title: "Full-stack developer at",
      we3Place: "",
      we3Time: "Fall 2023 session, T3 internship",
      we3Description: "Development of a page to perform tests on the company's projected margins. Use of C#, HTML, CSS, Telerik, JavaScript and SQL server.",
      we4Title: "Online Programmer for",
      we4Place: "",
      we4Time: "Winter 2023 session, T2 internship",
      we4Description: "Implementation of new features for a micro-service. Use of C#, GitLab and exploration of Amazon Web Services.",
      we5Title: "Programmer Analyst at ",
      we5Place: "",
      we5Time: "Summer and fall 2022 sessions, T1 internship and part-time job",
      we5Description: "Migration to Java of a PHP application for student management at the university. Use of Java, Spring Boot, HTML, CSS, GitLab and Docker.",
      education1Title: "Bachelor's degree in computer science cooperative program",
      education1Place: "Université de Sherbrooke (2021 - 2024)",
      education2Title: "College diploma in natural sciences",
      education2Place: "Collégial international Sainte-Anne (2019 - 2021)",
      education3Title: "Masters in Software Engineering",
      education3Place: "Future Project",
      project1Title: "Development of a video game - ZooBots (Fall 2024)",
      project1Description: "Implementation in four months of a video game. Use of Unity, C#, Gitlab and Blender.",
      project1View: "See the project",
      project2Title: "Development of a video game - Oneira (Winter 2024)",
      project2Description: "As part of the Ubisoft University Competition, implementation in three months of a video game prototype. Using Unity, C#, Gitlab and Blender.",
      project2View: "Watch the presentation video",
      project3Title: "Personal Challenges - Winter 2025", 
      project3Description: "In order to always progress in development, I challenge myself. Here the implementation of a tic tac toe game in Java. Using Java and Swing.",
      project3Note: "Note: This is just the beginning, other projects will be added in the future.",
      project3View: "GitHub Project",
      project4Title: "SoundCards - Winter 2025",
      project4Description: "SoundCards is an application designed to facilitate communication with non-verbal people. It is based on the use of visual pictograms associated with sounds that are played when clicked, allowing for simple and intuitive interaction. Developed with React, this web application is accessible from any device.",
      project4Note: "In development",
      projectIncoming: "Link to the upcoming github project.",
      project5Title: "EventAPI - Winter 2025",
      project5Description: "EventAPI is an API dedicated to event management. Developed in Java, it relies on a SQL database to ensure reliable and efficient management of event-related data.",
      project5Note: "In development",
      project5View: "Github project"
    },
    fr: {
      title: "Léandre Postal",
      aboutMeTitle: "À propos de moi",
      aboutMeText1: "Bonjour, je m'appelle Léandre et je suis récemment diplômé d’un baccalauréat en informatique de l’Université de Sherbrooke, en régime coopératif.",
      aboutMeText2: "Je suis motivé par les défis technologiques et par l'idée d'apporter des solutions innovantes grâce à mes compétences techniques et ma rigueur professionnelle.",
      interestsTitle: "Mes intérêts",
      sports: "Sports",
      sportsDescription: "J'aime les sports comme le triathlon, l'ultimate frisbee et le volley. Les sports d'extérieur m'intéressent aussi !",
      innovations: "Innovations",
      innovationsDescription: "J'aime explorer de nouvelles approches, outils et frameworks pour apporter des solutions performantes et adaptées aux besoins des utilisateurs.",
      graphics: "Graphisme",
      graphicsDescription: "J'aime concevoir, modéliser et dessiner de nouvelles idées. De Krita à Blender j'aime débuter des projets créatifs.",
      skillsTitle: "Mes compétences",
      teamwork: "Travail en équipe",
      curiosity: "Curiosité",
      leadership: "Leadership",
      workTitle: "Expériences de travail",
      educationTitle: "Éducation",
      projectsTitle: "Projets",
      downloadCV: "Télécharger le CV",
      footer: "© 2024 Léandre Postal. Tous droits réservés.",
      we1Title: "Analyste Programmeur pour",
      we1Place: "Université de sherbrooke",
      we1Time: "Sessions été et automne 2024, stage T4 et emploi à temps partiel",
      we1Description: "Développement d'un API REST en Java afin de creer et modifier des données des personnes étudiantes à l'université. Utilisation de Java, Spring Boot, GitLab et Docker.",
      we2Title: "Développeur full-stack chez",
      we2Place: "A&R Belley inc.",
      we2Time: "Session hiver 2024, emploi à temps partiel",
      we2Description: "Implementation d'une page de génération de contrats et d'envoi de documents. Utilisation de Blazor, C#, SQL server, Docusign API.",
      we3Title: "Développeur full-stack chez",
      we3Place: "A&R Belley inc.",
      we3Time: "Session automne 2023, stage T3",
      we3Description: "Développement d'une page permettant de faire des tests sur les marges projetées de l'entreprise. Utilisation de C#, HTML, CSS, Telerik, JavaScript et SQL server.",
      we4Title: "Programmeur Online pour",
      we4Place: "Ubisoft Sherbrooke",
      we4Time: "Session hiver 2023, stage T2",
      we4Description: "Implementation de nouvelles fonctionnalités pour un micro-service. Utilisation de C#, GitLab et exploration d'Amazon Web Services.",
      we5Title: "Analyste Programmeur pour",
      we5Place: "Université de sherbrooke",
      we5Time: "Sessions été et automne 2022, stage T1 et emploi à temps partiel",
      we5Description: "Migration en Java d'une application en PHP pour la gestion des étudiants à l'université.  Utilisation de Java, Spring Boot, HTML, CSS, GitLab et Docker.",
      education1Title: "Baccalauréat en informatique régime coopératif",
      education1Place: "Université de Sherbrooke (2021 - 2024)",
      education2Title: "Diplôme d'études collégiales mention sciences de la nature",
      education2Place: "Collégial international Sainte-Anne (2019 - 2021)",
      education3Title: "Maitrise en Génie Logiciel",
      education3Place: "Projet futur",
      project1Title: "Développement d'un jeu vidéo - ZooBots (Automne 2024)",
      project1Description: "Implémentation en quatre mois d'un jeu vidéo. Utilisation de Unity, C#, Gitlab et Blender.",
      project1View: "Voir le projet",
      project2Title: "Développement d'un jeu vidéo - Oneira (Hiver 2024)",
      project2Description: "Dans le cadre du Concours Universitaire Ubisoft, implementation en trois mois d'un prototype de jeu vidéo. Utilisation de Unity, C#, Gitlab et Blender.",
      project2View: "Voir la vidéo de présentation",
      project3Title: "Défis personnels - Hiver 2025", 
      project3Description: "Afin de toujours progresser en développement, je me lance des défis. Ici l'implementation d'un jeu de tic tac toe en Java. Utilisation de Java et Swing.",
      project3Note: "Note : Ce n'est que le début, d'autres projets seront ajoutés dans le futur.",
      project3View: "Projet GitHub",
      project4Title: "SoundCards - Hiver 2025",
      project4Description: "SoundCards est une application conçue pour faciliter la communication avec les personnes non verbales. Elle repose sur l'utilisation de pictogrammes visuels associés à des sons qui se jouent au clic, permettant une interaction simple et intuitive. Développée avec React, cette application web est accessible depuis n'importe quel appareil.",
      project4Note: "En cours de développement",
      projectIncoming: "Lien vers le projet github à venir.",
      project5Title: "EventAPI - Hiver 2025",
      project5Description: "EventAPI est une API dédiée à la gestion des événements. Développée en Java, elle s'appuie sur une base de données SQL pour assurer une gestion fiable et efficace des données liées aux événements.",
      project5Note: "En cours de développement",
      project5View: "Projet Github"
    }
  };

  function setLanguage(lang) {
    document.documentElement.lang = lang;
    const elements = document.querySelectorAll("[data-translate]");
    elements.forEach(el => {
      const key = el.dataset.translate;
      el.textContent = translations[lang][key];
    });
  }

  document.addEventListener("DOMContentLoaded", () => {
    setLanguage('fr'); // Default language
    document.getElementById("language-switcher").addEventListener("change", (e) => {
      setLanguage(e.target.value);
    });
  });